### ISSUE TITLE
pattern zur Tabellen ID Suche veraltet

### ISSUE THREAD

**Issue by b4nsh** [agroezinger/plg_content_agm_volleyimport#14]
Servus,

in der volleyimport.php in Zeile 214 muss das Pattern 
`$regex = '/{volleyImport\|([0-9]{4})\|([0-9]{1,4})\|([etsv]{1})}/';`

geändert werden in:

`$regex = '/{volleyImport\|([0-9]{4})\|([0-9]{1,5})\|([etsv]{1})}/';`
die 5 ist wichtig ;)

da neuerdings auch verstärkt Fünfstellige IDs verwendet werden. Andernfalls wird der Code nicht verarbeitet und keine Tabelle dargestellt.
Habe das bei unserem Verein jetzt mal per Hand angepasst.

Grüße

**Comment by agroezinger** [comment]
Hey,

danke fürs aufpassen. Das "Problem" wurde in Version 1.0.3. vom 17.07.2017 welche auf www.agmedia.de zum Download bereit steht, behoben. Ich habe leider vergessen die Dateien auch hier auf GitHub zu aktualisieren.

Liebe Grüße
