### ISSUE TITLE
Highlighting bei Tabelle funktioniert nicht

### ISSUE THREAD

**Issue by agroezinger** [agroezinger/plg_content_agm_volleyimport#2]
Highlighting des Vereins bei der Tabelle funktioniert nicht

**Comment by agroezinger** [comment]
Bitte wenn möglich Fehler genauer beschreiben:
=> {volleyImport ... Konfiguration mit angeben
=> Suchstring aus Pluginkonfiguration angeben

benötigt um Fehler nachzustellen, da bei mir das Highlighting funktioniert

**Comment by TheBearded1979** [comment]
Genauere Beschreibung:

Tabelle
{volleyImport|2014|51|t}
 
Spielplan
{volleyImport|2014|51|s}
 
Ergebnisse
{volleyImport|2014|51|e}

Suchstring aus PlugIn-Konfiguration: "Neckarsulmer Sport-Union", ohne die Anführungszeichen (auch getestet mit "Sport-Union"), Fehler tritt ebenfalls auf.

Fehler siehe http://www.nsu-volleyball.de/volleyimport

**Comment by TheBearded1979** [comment]
Mit 0.9.3 klappt das Highlighting jetzt.

**Comment by agroezinger** [comment]
Problem wurde mit dieser Version auch behoben :) Danke für die schnelle Rückmeldung
