### ISSUE TITLE
Sortierung in Tabellenanzeige unklar

### ISSUE THREAD

**Issue by TheBearded1979** [agroezinger/plg_content_agm_volleyimport#3]
Sortiert man in den Tabellen (z.B. Spielplan) nach Datum absteigend, ist die Anzeige unklar (siehe Screenshot). Dies gilt auch für andere Tabellen und andere Sortierfelder (z.B. Satzverhältnis in der Tabelle).

![volleyimport_sort_05052015](https://cloud.githubusercontent.com/assets/12242542/7463668/a7100068-f2bb-11e4-8624-e6ec559a6830.JPG)

**Comment by agroezinger** [comment]
Sortierung nach Datum unklar: Bug ist behoben
Sortierung Satzverhältnis: Neuer Fehler wird angelegt
