### ISSUE TITLE
Sortierung nach Satzverhältnis in der Tabelle

### ISSUE THREAD

**Issue by agroezinger** [agroezinger/plg_content_agm_volleyimport#4]
Sortierung ist unklar. Hier bedarf es auf jeden Fall einer eigenen Sortierfunktion als Erweiterung der DataTable Bibliothek. Die Frage ist, wie wichtig ist die Sortierung nach dem Ergebnis. Soll es überhaupt möglich sein nach dem Ergebnis zu sortieren

**Comment by TheBearded1979** [comment]
Aus meiner Sicht muss die Tabelle nicht sortierbar sein. Der User ist es gewöhnt (und erwartet es m.E. eigentlich), dass die Tabelle immer nach dem Tabellenplatz absteigend sortiert ist - so ist das eigentlich auch auf den Sport-Webseiten oder Livetickern (z.B. Bundesliga-Tabelle auf sport1.de, spiegel.de) gelöst. Die Sortierung ist maximal ein nice-to-have-Feature, die aber von vielen Usern nicht wahrgenommen wird oder zur Verwirrung führt.

**Comment by agroezinger** [comment]
Alles klar. Sortierung nach Ergebnis wird damit nicht möglich sein, gleichzeitig wird die Sortierfunktion standardmäßig deaktiviert sein (aktuell ist sie standardmäßig aktiviert)
