### ISSUE TITLE
Division by 0

### ISSUE THREAD

**Issue by agroezinger** [agroezinger/plg_content_agm_volleyimport#7]
Warning: Division by zero in /var/www/ud08_175/html/plugins/content/volleyimport/volleyimport.php on line 419

eben auf nsu-sport.de gesehen.

Problem wird sofort behoben

**Comment by TheBearded1979** [comment]
Wow,

du bist heute aber zügig unterwegs. ich schreibe grade noch an der
Fehlermeldung inkl. Screenshot...

Gruß,
Ben

2015-08-08 22:01 GMT+02:00 Alexander Grözinger <notifications@github.com>:

**Comment by agroezinger** [comment]
Brauchst du nicht. Fehler schon behoben. Update kommt in 2 min :)

Ja habe es zufällig gerade gesehen bei dir auf der Seite (solltest dennoch dein ERROR_REPORTING ausstellen. Ist nicht so praktisch auf ner LIVE-Seite :) )

**Comment by TheBearded1979** [comment]
Läuft wunderbar.

Danke für den Hinweis mit dem ERROR_REPORTING, das mach ich gleich mal.

Am 8. August 2015 um 22:08 schrieb Alexander Grözinger <
notifications@github.com>:

**Comment by agroezinger** [comment]
Fehler Doppelt. Siehe #8
